import { DealAnalysis } from './types'

export const mockDealAnalysis: DealAnalysis = {
  id: 'deal-001',
  dealName: '5041 Bayou Boulevard',
  propertyAddress: '5041 Bayou Blvd, Pensacola, FL 32503',
  submittedAt: '2026-04-18T14:32:00Z',
  score: 66,
  tier: 'YELLOW',
  dealReadiness: 'Proceed with conditions',
  subScores: {
    dataCompleteness: 16,
    rsfAlignment: 12,
    financialIntegrity: 14,
    leaseLeverage: 12,
    riskProfile: 8,
    documentCoverage: 4,
  },
  rsfReconciliation: {
    bomaTotalSF: 29452,
    rentRollOccupiedSF: 24847,
    deltaSF: 4605,
    deltaPercent: 18.5,
    estimatedAnnualRecovery: 51170,
    alertTriggered: true,
  },
  financialSummary: {
    totalAnnualRent: 276050,
    noi: 198750,
    capRate: 7.8,
    averageRentPSF: 11.11,
    vacancy: 15.6,
    arDelinquency: 8200,
  },
  walt: 42,
  redFlags: [
    {
      id: 'rf-001',
      severity: 'HIGH',
      category: 'RSF Discrepancy',
      description: 'BOMA total SF exceeds rent roll occupied SF by 4,605 SF (18.5%)',
      impact: 'Potential $51,170/year in CAM recovery not being billed',
      resolution: 'Request remeasurement or verify tenant SF allocations',
    },
    {
      id: 'rf-002',
      severity: 'HIGH',
      category: 'Missing Expiry',
      description: 'Suite 105 (Gulf Coast Insurance) has no documented lease expiration',
      impact: 'Cannot calculate WALT or assess rollover risk for 22% of income',
      resolution: 'Request complete lease document for Gulf Coast Insurance',
    },
    {
      id: 'rf-003',
      severity: 'MEDIUM',
      category: 'AR Delinquency',
      description: 'Coastal Fitness 60+ days past due on $8,200',
      impact: 'Collection risk on 12% of monthly income',
      resolution: 'Request AR aging report and payment history',
    },
    {
      id: 'rf-004',
      severity: 'MEDIUM',
      category: 'Concentration Risk',
      description: 'Top 2 tenants represent 58% of total income',
      impact: 'Significant exposure to tenant-specific risk',
    },
    {
      id: 'rf-005',
      severity: 'LOW',
      category: 'Near-term Rollover',
      description: 'Suite 201 lease expires in 8 months',
      impact: '14% of income at risk within year one',
    },
  ],
  whatToGetNext: [
    'Complete lease for Gulf Coast Insurance (Suite 105) - missing expiry date',
    'AR aging report with tenant payment history',
    'CAM reconciliation for prior year',
    'Estoppel certificates for top 3 tenants',
    'Property condition report',
  ],
  tenants: [
    {
      id: 't-001',
      name: 'Bank of America',
      suite: '100',
      rsf: 5500,
      bomaRsf: 6200,
      rsfDelta: 700,
      monthlyRent: 5500,
      annualRent: 66000,
      rentPSF: 12.0,
      leaseStart: '2020-03-01',
      leaseExpiry: '2030-02-28',
      monthsRemaining: 46,
      incomeConcentration: 24,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-002',
      name: 'Gulf Coast Insurance',
      suite: '105',
      rsf: 5000,
      bomaRsf: 5600,
      rsfDelta: 600,
      monthlyRent: 5000,
      annualRent: 60000,
      rentPSF: 12.0,
      leaseStart: '2018-06-01',
      leaseExpiry: null,
      monthsRemaining: null,
      incomeConcentration: 22,
      riskLevel: 'HIGH',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-003',
      name: 'Boost Mobile',
      suite: '110',
      rsf: 2200,
      bomaRsf: 2500,
      rsfDelta: 300,
      monthlyRent: 2420,
      annualRent: 29040,
      rentPSF: 13.2,
      leaseStart: '2023-01-15',
      leaseExpiry: '2028-01-14',
      monthsRemaining: 21,
      incomeConcentration: 11,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-004',
      name: 'Coastal Fitness',
      suite: '200',
      rsf: 4800,
      bomaRsf: 5400,
      rsfDelta: 600,
      monthlyRent: 4400,
      annualRent: 52800,
      rentPSF: 11.0,
      leaseStart: '2021-07-01',
      leaseExpiry: '2026-06-30',
      monthsRemaining: 2,
      incomeConcentration: 19,
      riskLevel: 'HIGH',
      arStatus: 'DELINQUENT',
      arBalance: 8200,
    },
    {
      id: 't-005',
      name: 'Gulf Breeze Dental',
      suite: '201',
      rsf: 3200,
      bomaRsf: 3600,
      rsfDelta: 400,
      monthlyRent: 3200,
      annualRent: 38400,
      rentPSF: 12.0,
      leaseStart: '2022-09-01',
      leaseExpiry: '2026-12-31',
      monthsRemaining: 8,
      incomeConcentration: 14,
      riskLevel: 'MEDIUM',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-006',
      name: 'Pensacola Tax Services',
      suite: '205',
      rsf: 1800,
      bomaRsf: 2100,
      rsfDelta: 300,
      monthlyRent: 1980,
      annualRent: 23760,
      rentPSF: 13.2,
      leaseStart: '2024-01-01',
      leaseExpiry: '2029-12-31',
      monthsRemaining: 44,
      incomeConcentration: 9,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
  ],
  leaseAbstracts: [
    {
      id: 'la-001',
      tenantName: 'Bank of America',
      suite: '100',
      rsf: 5500,
      commencementDate: '2020-03-01',
      expirationDate: '2030-02-28',
      baseRent: 66000,
      escalation: '3% annually',
      expenseStructure: 'NNN',
      camCap: null,
      renewalOptions: '2 x 5-year options',
      tiAllowance: 15,
      remeasurementRights: true,
      missingFields: [],
    },
    {
      id: 'la-002',
      tenantName: 'Gulf Coast Insurance',
      suite: '105',
      rsf: 5000,
      commencementDate: '2018-06-01',
      expirationDate: null,
      baseRent: 60000,
      escalation: 'Unknown',
      expenseStructure: 'NNN',
      camCap: null,
      renewalOptions: null,
      tiAllowance: null,
      remeasurementRights: false,
      missingFields: ['expirationDate', 'escalation', 'renewalOptions', 'tiAllowance'],
    },
    {
      id: 'la-003',
      tenantName: 'Boost Mobile',
      suite: '110',
      rsf: 2200,
      commencementDate: '2023-01-15',
      expirationDate: '2028-01-14',
      baseRent: 29040,
      escalation: '2.5% annually',
      expenseStructure: 'NNN',
      camCap: 5,
      renewalOptions: '1 x 5-year option',
      tiAllowance: 10,
      remeasurementRights: false,
      missingFields: [],
    },
    {
      id: 'la-004',
      tenantName: 'Coastal Fitness',
      suite: '200',
      rsf: 4800,
      commencementDate: '2021-07-01',
      expirationDate: '2026-06-30',
      baseRent: 52800,
      escalation: '2% annually',
      expenseStructure: 'MODIFIED_GROSS',
      camCap: 8,
      renewalOptions: '1 x 3-year option',
      tiAllowance: 20,
      remeasurementRights: false,
      missingFields: [],
    },
    {
      id: 'la-005',
      tenantName: 'Gulf Breeze Dental',
      suite: '201',
      rsf: 3200,
      commencementDate: '2022-09-01',
      expirationDate: '2026-12-31',
      baseRent: 38400,
      escalation: '3% annually',
      expenseStructure: 'NNN',
      camCap: null,
      renewalOptions: '2 x 5-year options',
      tiAllowance: 25,
      remeasurementRights: true,
      missingFields: [],
    },
  ],
  documents: [
    {
      id: 'doc-001',
      filename: 'Rent_Roll_April_2026.pdf',
      type: 'RENT_ROLL',
      uploadedAt: '2026-04-18T14:30:00Z',
      pageCount: 2,
      status: 'PROCESSED',
    },
    {
      id: 'doc-002',
      filename: 'BOMA_Measurement_2025.pdf',
      type: 'BOMA',
      uploadedAt: '2026-04-18T14:30:00Z',
      pageCount: 8,
      status: 'PROCESSED',
    },
    {
      id: 'doc-003',
      filename: 'Management_Report_Q1_2026.pdf',
      type: 'MANAGEMENT_REPORT',
      uploadedAt: '2026-04-18T14:31:00Z',
      pageCount: 12,
      status: 'PROCESSED',
    },
    {
      id: 'doc-004',
      filename: 'BankOfAmerica_Lease.pdf',
      type: 'LEASE',
      uploadedAt: '2026-04-18T14:31:00Z',
      pageCount: 24,
      status: 'PROCESSED',
    },
    {
      id: 'doc-005',
      filename: 'BoostMobile_Lease.pdf',
      type: 'LEASE',
      uploadedAt: '2026-04-18T14:32:00Z',
      pageCount: 18,
      status: 'PROCESSED',
    },
  ],
}

// Historical score data for the chart
export const scoreHistory = [
  { date: '2026-04-10', score: 43.5, documents: 2 },
  { date: '2026-04-12', score: 52, documents: 3 },
  { date: '2026-04-15', score: 58, documents: 4 },
  { date: '2026-04-18', score: 66, documents: 5 },
]

// Income concentration for pie chart
export const incomeConcentration = [
  { name: 'Bank of America', value: 24, fill: 'var(--chart-1)' },
  { name: 'Gulf Coast Insurance', value: 22, fill: 'var(--chart-2)' },
  { name: 'Coastal Fitness', value: 19, fill: 'var(--chart-3)' },
  { name: 'Gulf Breeze Dental', value: 14, fill: 'var(--chart-4)' },
  { name: 'Boost Mobile', value: 11, fill: 'var(--chart-5)' },
  { name: 'Other', value: 10, fill: 'var(--muted)' },
]

// WALT timeline data
export const waltTimeline = [
  { month: 'Jun 26', atRisk: 52800, secure: 217250 },
  { month: 'Dec 26', atRisk: 38400, secure: 178850 },
  { month: 'Jan 28', atRisk: 29040, secure: 149810 },
  { month: 'Dec 29', atRisk: 23760, secure: 126050 },
  { month: 'Feb 30', atRisk: 66000, secure: 60000 },
]
