import { DealAnalysis } from './types'

// Building totals
// Total BOMA RSF: 29,452 | Total USF: 25,610 | Building LF: 1.1500
// Total Recoverable Expenses: $148,240 (approx $5.02/SF on 29,452 SF)

export const mockDealAnalysis: DealAnalysis = {
  id: 'deal-001',
  dealName: '5041 Bayou Boulevard',
  propertyAddress: '5041 Bayou Blvd, Pensacola, FL 32503',
  submittedAt: '2026-04-18T14:32:00Z',
  score: 66,
  tier: 'YELLOW',
  subScores: {
    dataCompleteness: 16,
    rsfAlignment: 12,
    financialIntegrity: 14,
    leaseLeverage: 12,
    riskProfile: 8,
    documentCoverage: 4,
  },
  rsfReconciliation: {
    bomaTotalSF: 29452,
    rentRollOccupiedSF: 24847,
    deltaSF: 4605,
    deltaPercent: 18.5,
    estimatedAnnualRecovery: 51170,
    alertTriggered: true,
  },
  financialSummary: {
    totalAnnualRent: 276050,
    noi: 198750,
    capRate: 7.8,
    averageRentPSF: 11.11,
    vacancy: 15.6,
    arDelinquency: 8200,
  },
  walt: 42,

  // ── CAM Reconciliation ──────────────────────────────────────────────────────
  // Building total recoverable expenses: $148,240
  // Total BOMA RSF used as denominator: 29,452
  camReconciliation: {
    totalRecoverableExpenses: 148240,
    buildingTotalRSF: 29452,
    totalBilled: 98418,
    totalOwed: 124891,
    overUnderCollection: -26473, // negative = under-collected
    expenseCategories: [
      {
        glCode: '5100',
        description: 'Common Area Maintenance — Landscaping',
        totalAmount: 18600,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5200',
        description: 'Common Area Maintenance — Janitorial',
        totalAmount: 14400,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5300',
        description: 'Common Area Maintenance — HVAC',
        totalAmount: 22800,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5400',
        description: 'Property Insurance',
        totalAmount: 19200,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5500',
        description: 'Real Estate Taxes',
        totalAmount: 38400,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5600',
        description: 'Property Management Fee',
        totalAmount: 27600,
        recoverable: true,
        exclusionReason: null,
      },
      {
        glCode: '5700',
        description: 'Capital Expenditure — Roof Replacement',
        totalAmount: 42000,
        recoverable: false,
        exclusionReason: 'Capital expenditure — excluded by all leases',
      },
      {
        glCode: '5800',
        description: 'Leasing Commissions',
        totalAmount: 18500,
        recoverable: false,
        exclusionReason: 'Leasing cost — excluded by all leases',
      },
      {
        glCode: '5900',
        description: 'Depreciation',
        totalAmount: 8800,
        recoverable: false,
        exclusionReason: 'Non-cash item — excluded by all leases',
      },
    ],
    tenantCAMSummary: [
      {
        // Bank of America — Suite 100
        // Lease LF: 1.1667 (stated in lease). Implied LF: 5,500 / 4,714 = 1.1667
        // PRO-RATA: 5,500 / 29,452 = 18.67%
        // CAM Owed: $148,240 × 18.67% = $27,677
        // No CAM cap stated. No mgmt fee cap. No exclusions beyond standard.
        // ISSUE: Rent roll RSF used 5,500; BOMA shows 6,200. LF not reconciled to floor plan.
        tenantId: 't-001',
        tenantName: 'Bank of America',
        suite: '100',
        usf: 4714,
        rsf: 5500,
        loadFactor: 1.1667,
        leaseLoadFactor: 1.1667,
        loadFactorDelta: 0,
        proRataShare: 0.1867,
        totalRecoverableExpenses: 148240,
        camOwed: 27677,
        camBilled: 24600,
        overUnder: -3077,
        camCap: null,
        camCapApplied: false,
        grossUpApplied: false,
        expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
        mgmtFeeCapPct: null,
        baseYear: null,
        fixedCAM: false,
        controllableCap: null,
        anchorExclusion: false,
      },
      {
        // Gulf Coast Insurance — Suite 105
        // Lease LF: 1.1500 per lease exhibit. Implied LF: 5,000 / 4,348 = 1.1500
        // PRO-RATA: 5,000 / 29,452 = 16.98%
        // CAM Owed: $148,240 × 16.98% = $25,171
        // No lease expiry documented — billed as M-T-M estimate
        tenantId: 't-002',
        tenantName: 'Gulf Coast Insurance',
        suite: '105',
        usf: 4348,
        rsf: 5000,
        loadFactor: 1.15,
        leaseLoadFactor: 1.15,
        loadFactorDelta: 0,
        proRataShare: 0.1698,
        totalRecoverableExpenses: 148240,
        camOwed: 25171,
        camBilled: 0,
        overUnder: -25171,
        camCap: null,
        camCapApplied: false,
        grossUpApplied: false,
        expenseExclusions: ['Capital expenditures', 'Depreciation'],
        mgmtFeeCapPct: null,
        baseYear: null,
        fixedCAM: false,
        controllableCap: null,
        anchorExclusion: false,
      },
      {
        // Boost Mobile — Suite 110
        // Lease LF: 1.2000 (stated as 20% add-on). Implied LF: 2,200 / 1,833 = 1.2000
        // PRO-RATA: 2,200 / 29,452 = 7.47%
        // CAM Cap: 5% annual increase.
        // CAM Owed before cap: $148,240 × 7.47% = $11,073
        // Cap applied — prior year was $10,800; 5% cap = $11,340 — no cap applied this year
        tenantId: 't-003',
        tenantName: 'Boost Mobile',
        suite: '110',
        usf: 1833,
        rsf: 2200,
        loadFactor: 1.2,
        leaseLoadFactor: 1.2,
        loadFactorDelta: 0,
        proRataShare: 0.0747,
        totalRecoverableExpenses: 148240,
        camOwed: 11073,
        camBilled: 10800,
        overUnder: -273,
        camCap: 5,
        camCapApplied: false,
        grossUpApplied: false,
        expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
        mgmtFeeCapPct: 3,
        baseYear: null,
        fixedCAM: false,
        controllableCap: 5,
        anchorExclusion: false,
      },
      {
        // Coastal Fitness — Suite 200
        // DISCREPANCY: Rent roll RSF is 4,800. Lease states USF = 4,000, LF = 1.15 → RSF = 4,600.
        // Implied LF from rent roll: 4,800 / 4,000 = 1.2000. Lease LF: 1.1500. DELTA: +0.0500
        // This means Coastal Fitness is being OVER-charged on their pro-rata by ~3.3%.
        // Modified Gross — CAM cap 8%. No controllable distinction.
        // PRO-RATA using CORRECT lease RSF: 4,600 / 29,452 = 15.62%
        // CAM Owed: $148,240 × 15.62% = $23,155
        tenantId: 't-004',
        tenantName: 'Coastal Fitness',
        suite: '200',
        usf: 4000,
        rsf: 4800,
        loadFactor: 1.2,
        leaseLoadFactor: 1.15,
        loadFactorDelta: 0.05,
        proRataShare: 0.1629,
        totalRecoverableExpenses: 148240,
        camOwed: 23155,
        camBilled: 28800,
        overUnder: 5645,
        camCap: 8,
        camCapApplied: true,
        grossUpApplied: false,
        expenseExclusions: ['Capital expenditures', 'Depreciation'],
        mgmtFeeCapPct: 5,
        baseYear: null,
        fixedCAM: false,
        controllableCap: 8,
        anchorExclusion: false,
      },
      {
        // Gulf Breeze Dental — Suite 201
        // Lease LF: 1.1500 (stated). Implied LF: 3,200 / 2,783 = 1.1500 — matched.
        // PRO-RATA: 3,200 / 29,452 = 10.87%
        // CAM Owed: $148,240 × 10.87% = $16,114
        // Gross-up applied (occupancy 84.4% < 95% threshold)
        tenantId: 't-005',
        tenantName: 'Gulf Breeze Dental',
        suite: '201',
        usf: 2783,
        rsf: 3200,
        loadFactor: 1.15,
        leaseLoadFactor: 1.15,
        loadFactorDelta: 0,
        proRataShare: 0.1087,
        totalRecoverableExpenses: 148240,
        camOwed: 16114,
        camBilled: 18600,
        overUnder: 2486,
        camCap: null,
        camCapApplied: false,
        grossUpApplied: true,
        expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
        mgmtFeeCapPct: 3,
        baseYear: null,
        fixedCAM: false,
        controllableCap: null,
        anchorExclusion: false,
      },
      {
        // Pensacola Tax Services — Suite 205
        // FIXED CAM: $1,650/month flat — no annual reconciliation per lease.
        // No true-up. CAM billed = $19,800/yr flat.
        // Implied LF: 1,800 / 1,565 = 1.1501 — matched to lease.
        // PRO-RATA informational only (not used for billing under fixed CAM).
        tenantId: 't-006',
        tenantName: 'Pensacola Tax Services',
        suite: '205',
        usf: 1565,
        rsf: 1800,
        loadFactor: 1.1501,
        leaseLoadFactor: 1.15,
        loadFactorDelta: 0.0001,
        proRataShare: 0.0611,
        totalRecoverableExpenses: 148240,
        camOwed: 9052,
        camBilled: 15618,
        overUnder: 6566,
        camCap: null,
        camCapApplied: false,
        grossUpApplied: false,
        expenseExclusions: [],
        mgmtFeeCapPct: null,
        baseYear: null,
        fixedCAM: true,
        controllableCap: null,
        anchorExclusion: false,
      },
    ],
  },

  redFlags: [
    {
      id: 'rf-001',
      severity: 'HIGH',
      category: 'RSF Discrepancy',
      description: 'BOMA total SF exceeds rent roll occupied SF by 4,605 SF (18.5%)',
      impact: 'Potential $51,170/year in CAM recovery not being billed',
      resolution: 'Request remeasurement or verify tenant SF allocations',
    },
    {
      id: 'rf-002',
      severity: 'HIGH',
      category: 'Load Factor Discrepancy',
      description: 'Coastal Fitness (Suite 200): implied load factor 1.2000 vs. lease-stated 1.1500',
      impact: 'Tenant is being billed for 4,800 RSF; correct lease RSF is 4,600. Over-collection of $5,645/yr',
      resolution: 'Reconcile rent roll RSF to lease exhibit; adjust billing to 4,600 RSF',
    },
    {
      id: 'rf-003',
      severity: 'HIGH',
      category: 'Missing Expiry',
      description: 'Suite 105 (Gulf Coast Insurance) has no documented lease expiration',
      impact: 'Cannot calculate WALT or assess rollover risk for 22% of income',
      resolution: 'Request complete lease document for Gulf Coast Insurance',
    },
    {
      id: 'rf-004',
      severity: 'HIGH',
      category: 'CAM Billing Gap',
      description: 'Gulf Coast Insurance has $0 CAM billed — no expense recovery on 17% of building RSF',
      impact: '$25,171/year in recoverable expenses going unrecovered',
      resolution: 'Review lease CAM provisions and begin expense recovery billing immediately',
    },
    {
      id: 'rf-005',
      severity: 'MEDIUM',
      category: 'AR Delinquency',
      description: 'Coastal Fitness 60+ days past due on $8,200',
      impact: 'Collection risk on 12% of monthly income',
      resolution: 'Request AR aging report and payment history',
    },
    {
      id: 'rf-006',
      severity: 'MEDIUM',
      category: 'Concentration Risk',
      description: 'Top 2 tenants represent 58% of total income',
      impact: 'Significant exposure to tenant-specific risk',
    },
    {
      id: 'rf-007',
      severity: 'LOW',
      category: 'Near-term Rollover',
      description: 'Suite 201 lease expires in 8 months',
      impact: '14% of income at risk within year one',
    },
    {
      id: 'rf-008',
      severity: 'MEDIUM',
      category: 'Fixed CAM Overpayment',
      description: 'Pensacola Tax Services pays fixed CAM of $15,618/yr vs. correct amount of $9,052/yr',
      impact: 'Tenant overpaying $6,566/yr — creates legal exposure if tenant audits',
      resolution: 'Review fixed CAM clause; confirm if escalation has been applied improperly',
    },
  ],

  whatToGetNext: [
    'Complete lease for Gulf Coast Insurance (Suite 105) — missing expiry date and CAM provisions',
    'Itemized operating expense GL by line item (12-month trailing) for CAM reconciliation',
    'AR aging report with tenant payment history',
    'Prior year CAM reconciliation statements for all reconciling tenants',
    'Floor plan / as-built drawings to confirm USF for Coastal Fitness (Suite 200)',
    'Estoppel certificates for top 3 tenants',
  ],

  tenants: [
    {
      id: 't-001',
      name: 'Bank of America',
      suite: '100',
      usf: 4714,
      rsf: 5500,
      bomaRsf: 6200,
      rsfDelta: 700,
      loadFactor: 1.1667,
      leaseLoadFactor: 1.1667,
      proRataShare: 18.67,
      monthlyRent: 5500,
      annualRent: 66000,
      rentPSF: 12.0,
      leaseStart: '2020-03-01',
      leaseExpiry: '2030-02-28',
      monthsRemaining: 46,
      incomeConcentration: 24,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-002',
      name: 'Gulf Coast Insurance',
      suite: '105',
      usf: 4348,
      rsf: 5000,
      bomaRsf: 5600,
      rsfDelta: 600,
      loadFactor: 1.15,
      leaseLoadFactor: 1.15,
      proRataShare: 16.98,
      monthlyRent: 5000,
      annualRent: 60000,
      rentPSF: 12.0,
      leaseStart: '2018-06-01',
      leaseExpiry: null,
      monthsRemaining: null,
      incomeConcentration: 22,
      riskLevel: 'HIGH',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-003',
      name: 'Boost Mobile',
      suite: '110',
      usf: 1833,
      rsf: 2200,
      bomaRsf: 2500,
      rsfDelta: 300,
      loadFactor: 1.2,
      leaseLoadFactor: 1.2,
      proRataShare: 7.47,
      monthlyRent: 2420,
      annualRent: 29040,
      rentPSF: 13.2,
      leaseStart: '2023-01-15',
      leaseExpiry: '2028-01-14',
      monthsRemaining: 21,
      incomeConcentration: 11,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-004',
      name: 'Coastal Fitness',
      suite: '200',
      usf: 4000,
      rsf: 4800,
      bomaRsf: 5400,
      rsfDelta: 600,
      loadFactor: 1.2,
      leaseLoadFactor: 1.15,
      proRataShare: 16.29,
      monthlyRent: 4400,
      annualRent: 52800,
      rentPSF: 11.0,
      leaseStart: '2021-07-01',
      leaseExpiry: '2026-06-30',
      monthsRemaining: 2,
      incomeConcentration: 19,
      riskLevel: 'HIGH',
      arStatus: 'DELINQUENT',
      arBalance: 8200,
    },
    {
      id: 't-005',
      name: 'Gulf Breeze Dental',
      suite: '201',
      usf: 2783,
      rsf: 3200,
      bomaRsf: 3600,
      rsfDelta: 400,
      loadFactor: 1.15,
      leaseLoadFactor: 1.15,
      proRataShare: 10.87,
      monthlyRent: 3200,
      annualRent: 38400,
      rentPSF: 12.0,
      leaseStart: '2022-09-01',
      leaseExpiry: '2026-12-31',
      monthsRemaining: 8,
      incomeConcentration: 14,
      riskLevel: 'MEDIUM',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
    {
      id: 't-006',
      name: 'Pensacola Tax Services',
      suite: '205',
      usf: 1565,
      rsf: 1800,
      bomaRsf: 2100,
      rsfDelta: 300,
      loadFactor: 1.1501,
      leaseLoadFactor: 1.15,
      proRataShare: 6.11,
      monthlyRent: 1980,
      annualRent: 23760,
      rentPSF: 13.2,
      leaseStart: '2024-01-01',
      leaseExpiry: '2029-12-31',
      monthsRemaining: 44,
      incomeConcentration: 9,
      riskLevel: 'LOW',
      arStatus: 'CURRENT',
      arBalance: 0,
    },
  ],

  leaseAbstracts: [
    {
      id: 'la-001',
      tenantName: 'Bank of America',
      suite: '100',
      usf: 4714,
      rsf: 5500,
      loadFactor: 1.1667,
      commencementDate: '2020-03-01',
      expirationDate: '2030-02-28',
      baseRent: 66000,
      escalation: '3% annually',
      expenseStructure: 'NNN',
      camCap: null,
      camGrossUp: false,
      grossUpThreshold: null,
      expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
      mgmtFeeCap: null,
      baseYear: null,
      fixedCAM: false,
      controllableCamCap: null,
      anchorExclusion: false,
      renewalOptions: '2 x 5-year options',
      tiAllowance: 15,
      remeasurementRights: true,
      missingFields: [],
    },
    {
      id: 'la-002',
      tenantName: 'Gulf Coast Insurance',
      suite: '105',
      usf: 4348,
      rsf: 5000,
      loadFactor: 1.15,
      commencementDate: '2018-06-01',
      expirationDate: null,
      baseRent: 60000,
      escalation: 'Unknown',
      expenseStructure: 'NNN',
      camCap: null,
      camGrossUp: false,
      grossUpThreshold: null,
      expenseExclusions: ['Capital expenditures', 'Depreciation'],
      mgmtFeeCap: null,
      baseYear: null,
      fixedCAM: false,
      controllableCamCap: null,
      anchorExclusion: false,
      renewalOptions: null,
      tiAllowance: null,
      remeasurementRights: false,
      missingFields: ['expirationDate', 'escalation', 'renewalOptions', 'tiAllowance'],
    },
    {
      id: 'la-003',
      tenantName: 'Boost Mobile',
      suite: '110',
      usf: 1833,
      rsf: 2200,
      loadFactor: 1.2,
      commencementDate: '2023-01-15',
      expirationDate: '2028-01-14',
      baseRent: 29040,
      escalation: '2.5% annually',
      expenseStructure: 'NNN',
      camCap: 5,
      camGrossUp: false,
      grossUpThreshold: null,
      expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
      mgmtFeeCap: 3,
      baseYear: null,
      fixedCAM: false,
      controllableCamCap: 5,
      anchorExclusion: false,
      renewalOptions: '1 x 5-year option',
      tiAllowance: 10,
      remeasurementRights: false,
      missingFields: [],
    },
    {
      id: 'la-004',
      tenantName: 'Coastal Fitness',
      suite: '200',
      usf: 4000,
      rsf: 4800,
      loadFactor: 1.15,
      commencementDate: '2021-07-01',
      expirationDate: '2026-06-30',
      baseRent: 52800,
      escalation: '2% annually',
      expenseStructure: 'MODIFIED_GROSS',
      camCap: 8,
      camGrossUp: false,
      grossUpThreshold: null,
      expenseExclusions: ['Capital expenditures', 'Depreciation'],
      mgmtFeeCap: 5,
      baseYear: null,
      fixedCAM: false,
      controllableCamCap: 8,
      anchorExclusion: false,
      renewalOptions: '1 x 3-year option',
      tiAllowance: 20,
      remeasurementRights: false,
      missingFields: [],
    },
    {
      id: 'la-005',
      tenantName: 'Gulf Breeze Dental',
      suite: '201',
      usf: 2783,
      rsf: 3200,
      loadFactor: 1.15,
      commencementDate: '2022-09-01',
      expirationDate: '2026-12-31',
      baseRent: 38400,
      escalation: '3% annually',
      expenseStructure: 'NNN',
      camCap: null,
      camGrossUp: true,
      grossUpThreshold: 95,
      expenseExclusions: ['Capital expenditures', 'Leasing commissions', 'Depreciation'],
      mgmtFeeCap: 3,
      baseYear: null,
      fixedCAM: false,
      controllableCamCap: null,
      anchorExclusion: false,
      renewalOptions: '2 x 5-year options',
      tiAllowance: 25,
      remeasurementRights: true,
      missingFields: [],
    },
    {
      id: 'la-006',
      tenantName: 'Pensacola Tax Services',
      suite: '205',
      usf: 1565,
      rsf: 1800,
      loadFactor: 1.15,
      commencementDate: '2024-01-01',
      expirationDate: '2029-12-31',
      baseRent: 23760,
      escalation: '3% annually',
      expenseStructure: 'MODIFIED_GROSS',
      camCap: null,
      camGrossUp: false,
      grossUpThreshold: null,
      expenseExclusions: [],
      mgmtFeeCap: null,
      baseYear: null,
      fixedCAM: true,
      controllableCamCap: null,
      anchorExclusion: false,
      renewalOptions: '1 x 5-year option',
      tiAllowance: 8,
      remeasurementRights: false,
      missingFields: [],
    },
  ],

  documents: [
    {
      id: 'doc-001',
      filename: 'Rent_Roll_April_2026.pdf',
      type: 'RENT_ROLL',
      uploadedAt: '2026-04-18T14:30:00Z',
      pageCount: 2,
      status: 'PROCESSED',
    },
    {
      id: 'doc-002',
      filename: 'BOMA_Measurement_2025.pdf',
      type: 'BOMA',
      uploadedAt: '2026-04-18T14:30:00Z',
      pageCount: 8,
      status: 'PROCESSED',
    },
    {
      id: 'doc-003',
      filename: 'Management_Report_Q1_2026.pdf',
      type: 'MANAGEMENT_REPORT',
      uploadedAt: '2026-04-18T14:31:00Z',
      pageCount: 12,
      status: 'PROCESSED',
    },
    {
      id: 'doc-004',
      filename: 'BankOfAmerica_Lease.pdf',
      type: 'LEASE',
      uploadedAt: '2026-04-18T14:31:00Z',
      pageCount: 24,
      status: 'PROCESSED',
    },
    {
      id: 'doc-005',
      filename: 'BoostMobile_Lease.pdf',
      type: 'LEASE',
      uploadedAt: '2026-04-18T14:32:00Z',
      pageCount: 18,
      status: 'PROCESSED',
    },
  ],
}

// Historical score data for the chart
export const scoreHistory = [
  { date: '2026-04-10', score: 43.5, documents: 2 },
  { date: '2026-04-12', score: 52, documents: 3 },
  { date: '2026-04-15', score: 58, documents: 4 },
  { date: '2026-04-18', score: 66, documents: 5 },
]

// Income concentration for pie chart
export const incomeConcentration = [
  { name: 'Bank of America', value: 24, fill: 'var(--chart-1)' },
  { name: 'Gulf Coast Insurance', value: 22, fill: 'var(--chart-2)' },
  { name: 'Coastal Fitness', value: 19, fill: 'var(--chart-3)' },
  { name: 'Gulf Breeze Dental', value: 14, fill: 'var(--chart-4)' },
  { name: 'Boost Mobile', value: 11, fill: 'var(--chart-5)' },
  { name: 'Other', value: 10, fill: 'var(--muted)' },
]

// WALT timeline data
export const waltTimeline = [
  { month: 'Jun 26', atRisk: 52800, secure: 217250 },
  { month: 'Dec 26', atRisk: 38400, secure: 178850 },
  { month: 'Jan 28', atRisk: 29040, secure: 149810 },
  { month: 'Dec 29', atRisk: 23760, secure: 126050 },
  { month: 'Feb 30', atRisk: 66000, secure: 60000 },
]
